import type { LucideIcon } from "lucide-react";
import type { ReactNode } from "react";

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description: string; actions?: ReactNode }) { return <header className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div className="min-w-0">{eyebrow && <p className="text-xs font-black uppercase tracking-[0.22em] text-orange-400">{eyebrow}</p>}<h1 className="mt-2 text-3xl font-black tracking-[-0.035em] text-white sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500 sm:text-base">{description}</p></div>{actions && <div className="flex shrink-0 flex-wrap gap-2">{actions}</div>}</header>; }

export function MetricCard({ label, value, detail, icon: Icon, tone = "neutral" }: { label: string; value: string; detail?: string; icon?: LucideIcon; tone?: "positive" | "warning" | "danger" | "info" | "neutral" }) { const colors = { positive: "text-emerald-400 bg-emerald-500/10 border-emerald-500/15", warning: "text-orange-400 bg-orange-500/10 border-orange-500/15", danger: "text-red-400 bg-red-500/10 border-red-500/15", info: "text-sky-400 bg-sky-500/10 border-sky-500/15", neutral: "text-zinc-300 bg-white/[0.035] border-white/[0.07]" }[tone]; return <article className="group relative overflow-hidden rounded-2xl border border-white/[0.07] bg-gradient-to-br from-zinc-900 to-zinc-950 p-5 shadow-xl shadow-black/10 transition duration-200 hover:-translate-y-0.5 hover:border-white/[0.13]"><div className="flex items-start justify-between gap-3"><p className="text-xs font-bold uppercase tracking-[0.12em] text-zinc-600">{label}</p>{Icon && <span className={`flex h-9 w-9 items-center justify-center rounded-xl border ${colors}`}><Icon size={17} /></span>}</div><p className={`mt-4 break-words text-3xl font-black tracking-[-0.04em] ${colors.split(" ")[0]}`}>{value}</p>{detail && <p className="mt-2 text-xs leading-5 text-zinc-600">{detail}</p>}</article>; }

export function SectionCard({ title, description, action, children, className = "" }: { title?: string; description?: string; action?: ReactNode; children: ReactNode; className?: string }) { return <section className={`rounded-2xl border border-white/[0.07] bg-zinc-900/80 p-5 shadow-xl shadow-black/10 sm:p-6 ${className}`}>{(title || action) && <div className="mb-5 flex items-start justify-between gap-4"><div>{title && <h2 className="text-lg font-black text-white sm:text-xl">{title}</h2>}{description && <p className="mt-1 text-sm text-zinc-500">{description}</p>}</div>{action}</div>}{children}</section>; }

export function ProgressBar({ value, label, tone = "orange" }: { value: number; label?: string; tone?: "orange" | "green" | "blue" | "red" }) { const color = { orange: "bg-orange-500", green: "bg-emerald-500", blue: "bg-sky-500", red: "bg-red-500" }[tone]; const safe = Math.min(100, Math.max(0, value)); return <div>{label && <div className="mb-2 flex justify-between text-xs font-semibold"><span className="text-zinc-500">{label}</span><span className="text-zinc-300">{safe}%</span></div>}<div className="h-2 overflow-hidden rounded-full bg-zinc-800"><div className={`h-full rounded-full transition-all duration-500 ${color}`} style={{ width: `${safe}%` }} /></div></div>; }

export function EmptyState({ icon: Icon, title, description, action }: { icon: LucideIcon; title: string; description: string; action?: ReactNode }) { return <div className="rounded-2xl border border-dashed border-white/10 bg-zinc-900/40 px-6 py-14 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-white/[0.04] text-zinc-600"><Icon size={27} /></span><h2 className="mt-5 text-lg font-bold text-white">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-zinc-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div>; }

export function MiniBarChart({ data }: { data: Array<{ label: string; primary: number; secondary?: number }> }) { const max = Math.max(1, ...data.flatMap((item) => [item.primary, item.secondary ?? 0])); return <div className="flex h-48 items-end gap-3 border-b border-white/[0.07] px-1 pt-6">{data.map((item) => <div key={item.label} className="flex h-full min-w-0 flex-1 flex-col justify-end gap-1"><div className="flex flex-1 items-end justify-center gap-1"><div title={String(item.primary)} className="w-full max-w-7 rounded-t-md bg-emerald-500 transition hover:bg-emerald-400" style={{ height: `${Math.max(4, item.primary / max * 100)}%` }} />{item.secondary !== undefined && <div title={String(item.secondary)} className="w-full max-w-7 rounded-t-md bg-red-500 transition hover:bg-red-400" style={{ height: `${Math.max(4, item.secondary / max * 100)}%` }} />}</div><p className="truncate py-2 text-center text-[10px] font-semibold text-zinc-600">{item.label}</p></div>)}</div>; }
