"use client";
import Link from "next/link";
import { AlertCircle, Bell, BellOff, Loader2, RefreshCw } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import type { SystemNotification } from "@/types/notification";

type Data = { notifications: SystemNotification[]; total: number };
export function NotificationCenter() {
  const [open, setOpen] = useState(false); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState(false); const root = useRef<HTMLDivElement>(null);
  async function load() { try { setLoading(true); setError(false); const response = await fetch("/api/notifications?limit=6", { cache: "no-store" }); if (!response.ok) throw new Error(); setData(await response.json()); } catch { setError(true); } finally { setLoading(false); } }
  useEffect(() => { if (open && !data && !loading) void load(); }, [open, data, loading]);
  useEffect(() => { const close = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node)) setOpen(false); }; document.addEventListener("mousedown", close); return () => document.removeEventListener("mousedown", close); }, []);
  return <div ref={root} className="relative"><button onClick={() => setOpen((value) => !value)} title="Notificações" className="relative flex h-11 w-11 items-center justify-center rounded-xl border border-white/[0.07] bg-white/[0.035] text-zinc-500 hover:text-orange-400"><Bell size={18} />{data && data.total > 0 && <span className="absolute -right-1.5 -top-1.5 flex min-h-5 min-w-5 items-center justify-center rounded-full border-2 border-[#0b0b0d] bg-red-500 px-1 text-[10px] font-black text-white">{data.total > 99 ? "99+" : data.total}</span>}</button>{open && <div className="fixed left-4 right-4 top-20 z-50 overflow-hidden rounded-2xl border border-white/10 bg-zinc-950 shadow-2xl sm:absolute sm:left-auto sm:right-0 sm:top-14 sm:w-[390px]"><div className="flex items-center justify-between border-b border-white/[0.07] p-4"><div><h2 className="font-bold text-white">Notificações</h2><p className="text-xs text-zinc-500">Pendências em tempo real</p></div>{data && <span className="rounded-full bg-red-500/10 px-2.5 py-1 text-xs font-bold text-red-400">{data.total}</span>}</div><div className="max-h-[420px] overflow-y-auto p-2">{loading ? <State icon={Loader2} text="Carregando..." spin /> : error ? <div className="p-6 text-center"><State icon={AlertCircle} text="Falha ao carregar." /><button onClick={load} className="inline-flex items-center gap-2 text-sm font-bold text-orange-400"><RefreshCw size={15} />Tentar novamente</button></div> : data?.notifications.length ? data.notifications.map((item) => <NotificationItem key={item.id} item={item} onClick={() => setOpen(false)} />) : <State icon={BellOff} text="Nenhuma pendência encontrada." />}</div><Link href="/notificacoes" onClick={() => setOpen(false)} className="block border-t border-white/[0.07] p-3 text-center text-sm font-bold text-orange-400">Ver todas</Link></div>}</div>;
}
export function NotificationItem({ item, onClick }: { item: SystemNotification; onClick?: () => void }) { const dot = { CRITICAL: "bg-red-500", WARNING: "bg-orange-500", INFO: "bg-blue-500" }[item.priority]; return <Link href={item.href} onClick={onClick} className="flex gap-3 rounded-xl p-3 hover:bg-white/[0.04]"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${dot}`} /><div className="min-w-0"><div className="flex justify-between gap-2"><p className="text-sm font-bold text-white">{item.title}</p><span className="shrink-0 text-[9px] font-bold text-zinc-600">{item.type.replaceAll("_", " ")}</span></div><p className="mt-1 line-clamp-2 text-xs leading-5 text-zinc-500">{item.description}</p><p className="mt-1 text-[11px] text-zinc-600">Prazo: {new Date(item.dueDate).toLocaleString("pt-BR", { dateStyle: "short", timeStyle: "short" })}</p></div></Link>; }
function State({ icon: Icon, text, spin = false }: { icon: typeof Bell; text: string; spin?: boolean }) { return <div className="flex flex-col items-center gap-3 p-8 text-sm text-zinc-500"><Icon size={24} className={spin ? "animate-spin" : ""} />{text}</div>; }
