"use client";
import { AlertCircle, BellOff, Loader2, RefreshCw } from "lucide-react";
import { useCallback, useEffect, useMemo, useState } from "react";
import { NotificationItem } from "./NotificationCenter";
import type { NotificationPriority, SystemNotification } from "@/types/notification";
type Filter = "ALL" | NotificationPriority;
export function NotificationsPage() {
  const [items, setItems] = useState<SystemNotification[]>([]); const [counts, setCounts] = useState({ critical: 0, warning: 0, info: 0 }); const [filter, setFilter] = useState<Filter>("ALL"); const [loading, setLoading] = useState(true); const [error, setError] = useState(false);
  const load = useCallback(async () => { try { setLoading(true); setError(false); const response = await fetch("/api/notifications", { cache: "no-store" }); if (!response.ok) throw new Error(); const data = await response.json(); setItems(data.notifications); setCounts(data.counts); } catch { setError(true); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); const filtered = useMemo(() => filter === "ALL" ? items : items.filter((item) => item.priority === filter), [items, filter]);
  if (loading) return <State icon={Loader2} text="Carregando notificações..." spin />; if (error) return <div className="rounded-2xl border border-red-500/20 bg-red-500/5 p-10 text-center"><AlertCircle className="mx-auto text-red-400" size={34} /><h2 className="mt-4 text-xl font-bold text-white">Não foi possível carregar</h2><button onClick={load} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-orange-500 px-5 py-3 text-sm font-bold text-white"><RefreshCw size={16} />Tentar novamente</button></div>;
  return <><div className="mb-6 grid gap-4 sm:grid-cols-3"><Count label="Críticas" value={counts.critical} color="text-red-400" /><Count label="Atenção" value={counts.warning} color="text-orange-400" /><Count label="Informativas" value={counts.info} color="text-blue-400" /></div><div className="mb-5 flex flex-wrap gap-2">{([['ALL','Todas'],['CRITICAL','Críticas'],['WARNING','Atenção'],['INFO','Informativas']] as const).map(([value,label]) => <button key={value} onClick={() => setFilter(value)} className={`rounded-xl px-4 py-2 text-sm font-bold ${filter === value ? "bg-orange-500 text-white" : "bg-zinc-900 text-zinc-400"}`}>{label}</button>)}</div><section className="rounded-2xl border border-white/[0.07] bg-zinc-900 p-2">{filtered.length ? filtered.map((item) => <NotificationItem key={item.id} item={item} />) : <State icon={BellOff} text="Nenhuma notificação nesta categoria." />}</section></>;
}
function Count({ label, value, color }: { label: string; value: number; color: string }) { return <div className="rounded-2xl border border-white/[0.07] bg-zinc-900 p-5"><p className="text-sm text-zinc-500">{label}</p><p className={`mt-2 text-3xl font-black ${color}`}>{value}</p></div>; }
function State({ icon: Icon, text, spin = false }: { icon: typeof BellOff; text: string; spin?: boolean }) { return <div className="flex min-h-64 flex-col items-center justify-center gap-3 text-zinc-500"><Icon className={spin ? "animate-spin" : ""} size={32} /><p>{text}</p></div>; }
